version: '3'

services:
  web:
    build: .
    ports:
      - "80:80"
    volumes:
      - .:/app
      - ./static:/app/static
    environment:
      - FLASK_ENV=production
      - CLIENT_ID=your_client_id
      - CLIENT_SECRET=your_client_secret
      - SECRET_KEY=your_secret_key
      - SCOPE=your_scope
    depends_on:
      - db

  db:
    image: sqlite3
    volumes:
      - ./db:/data/db

volumes:
  db: